### ISSUE TITLE
Error during async connect

### ISSUE THREAD

**Issue by tshand** [sbabcock23/hass-tryfi#41]
Logger: custom_components.tryfi.config_flow
Source: custom_components/tryfi/__init__.py:88
Integration: TryFi ([documentation](https://github.com/sbabcock23/hass-tryfi), [issues](https://github.com/sbabcock23/hass-tryfi/issues))
First occurred: April 20, 2022, 11:15:32 PM (2 occurrences)
Last logged: April 20, 2022, 11:17:14 PM

Unexpected exception
Traceback (most recent call last):
  File "/config/custom_components/tryfi/__init__.py", line 83, in async_connect_or_timeout
    userId = tryfi._userId
AttributeError: 'PyTryFi' object has no attribute '_userId'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/config/custom_components/tryfi/config_flow.py", line 84, in async_step_user
    info = await validate_input(self.hass, user_input)
  File "/config/custom_components/tryfi/config_flow.py", line 52, in validate_input
    info = await async_connect_or_timeout(hass, tryfi)
  File "/config/custom_components/tryfi/__init__.py", line 88, in async_connect_or_timeout
    raise CannotConnect from err
custom_components.tryfi.CannotConnect

**Comment by sbabcock23** [comment]
@tshand  - is this still an issue?

**Comment by tshand** [comment]
I don't think so. Been working fine recently
