### ISSUE TITLE
unhandled exception in latest update

### ISSUE THREAD

**Issue by estiens** [sbabcock23/hass-tryfi#45]
```
  File "/usr/local/lib/python3.9/site-packages/pytryfi/fiDevice.py", line 92, in isLost
    if self._mode == PET_MODE_LOST:
AttributeError: 'FiDevice' object has no attribute '_mode'
```

```
2022-05-02 21:07:26 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 137, in _handle_refresh_interval
    await self._async_refresh(log_failures=True, scheduled=True)
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 268, in _async_refresh
    update_callback()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 328, in _handle_coordinator_update
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 532, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 570, in _async_write_ha_state
    state = self._stringify_state(available)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 538, in _stringify_state
    if (state := self.state) is None:
  File "/usr/src/homeassistant/homeassistant/components/select/__init__.py", line 93, in state
    if self.current_option is None or self.current_option not in self.options:
  File "/config/custom_components/tryfi/select.py", line 55, in current_option
    if self.pet.isLost:
  File "/usr/local/lib/python3.9/site-packages/pytryfi/fiPet.py", line 289, in isLost
    return self.device.isLost
  File "/usr/local/lib/python3.9/site-packages/pytryfi/fiDevice.py", line 92, in isLost
    if self._mode == PET_MODE_LOST:
AttributeError: 'FiDevice' object has no attribute '_mode'
2022-05-02 21:07:36 ERROR (MainThread) [homeassistant] Error doing
```

**Comment by sbabcock23** [comment]
Hi @estiens ,

Can you enable debug mode and share the output of anything tryfi related?

**Comment by estiens** [comment]
Will do

**Comment by estiens** [comment]
Deleted __pycache__ and let it reinstall pytryfi and now it works a charm...

sorry for false alarm!
