### ISSUE TITLE
Started getting two errors today.  

### ISSUE THREAD

**Issue by waite75585** [sbabcock23/hass-tryfi#64]
Logger: homeassistant.components.select
Source: custom_components/tryfi/select.py:55
Integration: Select (documentation, issues)
First occurred: 6:53:19 PM (2 occurrences)
Last logged: 6:53:20 PM

Error adding entities for domain select with platform tryfi
Error while setting up tryfi platform for select
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 442, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 717, in _async_add_entity
    await entity.add_to_platform_finish()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 807, in add_to_platform_finish
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 559, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 600, in _async_write_ha_state
    state = self._stringify_state(available)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 565, in _stringify_state
    if (state := self.state) is None:
  File "/usr/src/homeassistant/homeassistant/components/select/__init__.py", line 147, in state
    if self.current_option is None or self.current_option not in self.options:
  File "/config/custom_components/tryfi/select.py", line 55, in current_option
    if self.pet.isLost:
  File "/usr/local/lib/python3.10/site-packages/pytryfi/fiPet.py", line 362, in isLost
    return self.device.isLost
  File "/usr/local/lib/python3.10/site-packages/pytryfi/fiDevice.py", line 92, in isLost
    if self._mode == PET_MODE_LOST:
AttributeError: 'FiDevice' object has no attribute '_mode'

Logger: homeassistant.components.light
Source: custom_components/tryfi/light.py:74
Integration: Light (documentation, issues)
First occurred: 6:53:19 PM (2 occurrences)
Last logged: 6:53:19 PM

Error adding entities for domain light with platform tryfi
Error while setting up tryfi platform for light
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 442, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 717, in _async_add_entity
    await entity.add_to_platform_finish()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 807, in add_to_platform_finish
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 559, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 600, in _async_write_ha_state
    state = self._stringify_state(available)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 565, in _stringify_state
    if (state := self.state) is None:
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1000, in state
    if (is_on := self.is_on) is None:
  File "/config/custom_components/tryfi/light.py", line 74, in is_on
    return bool(self.pet.device.ledOn)
  File "/usr/local/lib/python3.10/site-packages/pytryfi/fiDevice.py", line 68, in ledOn
    return self._ledOn
AttributeError: 'FiDevice' object has no attribute '_ledOn'

**Comment by waite75585** [comment]
This error originated from a custom integration.

Logger: homeassistant
Source: custom_components/tryfi/light.py:74
Integration: TryFi (documentation, issues)
First occurred: 6:53:32 PM (47 occurrences)
Last logged: 7:01:56 PM

Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 182, in _handle_refresh_interval
    await self._async_refresh(log_failures=True, scheduled=True)
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 330, in _async_refresh
    self.async_update_listeners()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 135, in async_update_listeners
    update_callback()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 390, in _handle_coordinator_update
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 559, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 600, in _async_write_ha_state
    state = self._stringify_state(available)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 565, in _stringify_state
    if (state := self.state) is None:
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1000, in state
    if (is_on := self.is_on) is None:
  File "/config/custom_components/tryfi/light.py", line 74, in is_on
    return bool(self.pet.device.ledOn)
  File "/usr/local/lib/python3.10/site-packages/pytryfi/fiDevice.py", line 68, in ledOn
    return self._ledOn
AttributeError: 'FiDevice' object has no attribute '_ledOn'

**Comment by jldeen** [comment]
@waite75585 A bunch of us began seeing the same behavior you're describing (see previous issues). @sbabcock23 just pushed an update less than an hour ago to both this project and the underlying package pytryfi. Can you update to the latest version (0.0.19) and see if your issue is resolved?

**Comment by waite75585** [comment]
sorry for the duplicate report didn't look like the same issue.  I seem to be good, thanks so much for quickly fixing..
