### ISSUE TITLE
TryFi integration fails to load 

### ISSUE THREAD

**Issue by sekarashwin** [sbabcock23/hass-tryfi#65]
My setup :
* Home Assistant OS (2023.4.2)
* TryFi integration from HACS. (v 0.0.19)

TryFi integration fails to with error `'PyTryFi' object has no attribute '_pets'`

I have removed/redownloading HASS-TryFi and also tried several full reboots of my Home Assistant OS machine, etc. Logs are included below, personal information has been removed.

```2023-04-11 13:38:31.013 ERROR (MainThread) [homeassistant.components.device_tracker] Error while setting up tryfi platform for device_tracker
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 304, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/tryfi/device_tracker.py", line 32, in async_setup_entry
    for pet in tryfi.pets:
  File "/usr/local/lib/python3.10/site-packages/pytryfi/__init__.py", line 171, in pets
    return self._pets
AttributeError: 'PyTryFi' object has no attribute '_pets'
2023-04-11 13:38:31.026 ERROR (MainThread) [homeassistant.components.light] Error while setting up tryfi platform for light
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 304, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/tryfi/light.py", line 34, in async_setup_entry
    for pet in tryfi.pets:
  File "/usr/local/lib/python3.10/site-packages/pytryfi/__init__.py", line 171, in pets
    return self._pets
AttributeError: 'PyTryFi' object has no attribute '_pets'
2023-04-11 13:38:31.036 ERROR (MainThread) [homeassistant.components.sensor] Error while setting up tryfi platform for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 304, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/tryfi/sensor.py", line 34, in async_setup_entry
    for pet in tryfi.pets:
  File "/usr/local/lib/python3.10/site-packages/pytryfi/__init__.py", line 171, in pets
    return self._pets
AttributeError: 'PyTryFi' object has no attribute '_pets'
2023-04-11 13:38:31.041 ERROR (MainThread) [homeassistant.components.select] Error while setting up tryfi platform for select
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 304, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/tryfi/select.py", line 13, in async_setup_entry
    for pet in tryfi.pets:
  File "/usr/local/lib/python3.10/site-packages/pytryfi/__init__.py", line 171, in pets
    return self._pets
AttributeError: 'PyTryFi' object has no attribute '_pets'
2023-04-11 13:38:31.047 ERROR (MainThread) [homeassistant.components.binary_sensor] Error while setting up tryfi platform for binary_sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 304, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/tryfi/binary_sensor.py", line 20, in async_setup_entry
    for pet in tryfi.pets:
  File "/usr/local/lib/python3.10/site-packages/pytryfi/__init__.py", line 171, in pets
    return self._pets
AttributeError: 'PyTryFi' object has no attribute '_pets'
```

**Comment by twister36** [comment]
Mine stopped working as well. I reinstalled the add-on and it will connect to my account, but shows no collars or bases anymore.

**Comment by sambourne1** [comment]
also seeing this issue

**Comment by jhanluis1223** [comment]
Same thing here to, I tried removing HASS TryFI, Disabling the service, reloading the service and rebooting HA many times and still no luck.

**Comment by loafbutts** [comment]
I'm afraid I'm in the same boat. Sensors stopped updating yesterday, and when I tried removing the integration and re-adding it today, none of the entities populated. My log looks basically the same as @sekarashwin 's, with "AttributeError: 'PyTryFi' object has no attribute '_pets'" seeming to be the sticking point.

**Comment by sbabcock23** [comment]
Hi Everyone,

It appears TryFi changed something. I am currently investigating.

**Comment by sbabcock23** [comment]
Version 0.0.20 has been released. There were changes by TryFi that caused some of these problems which was fixed in the pytryfi library. Please confirm and close if everything is now working.

**Comment by jhanluis1223** [comment]
Yayy its all working now! Thanks a lot!

**Comment by loafbutts** [comment]
Everything's good for me now, too. Thanks so much for sorting this one out so quickly, @sbabcock23 !

**Comment by twister36** [comment]
Also working for me after the upgrade. Thank you.
