### ISSUE TITLE
Reinstall causes only base to be added, no collar/sensor entities - log mentions no _breed attribute

### ISSUE THREAD

**Issue by loafbutts** [sbabcock23/hass-tryfi#67]
Hello again! I think an update on Fi's end may have broken the integration again.

I just activated a new collar on my Fi account, and reinstalled the integration to update my entities, but unfortunately it only found the base, not the collars, etc. Even the entities for the older collar are gone. There's an error in the log very similar to past incidents of Fi changing something and gumming up the works, this time with the spoiler attribute being "_breed".

Relevant log entry:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 455, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 563, in _async_add_entity
    device_info = entity.device_info
  File "/config/custom_components/tryfi/device_tracker.py", line 91, in device_info
    "model": self.pet.breed,
  File "/usr/local/lib/python3.10/site-packages/pytryfi/fiPet.py", line 291, in breed
    return self._breed
AttributeError: 'FiPet' object has no attribute '_breed'

**Comment by loafbutts** [comment]
Just me on this one? I've tried re-adding the integration since, and now it doesn't populate any entities at all, not even the base.

**Comment by loafbutts** [comment]
Found a workaround! Simply going into /config/custom_components/tryfi/ , editing binary_sensor.py, device_tracker.py, light.py, select.py, and sensor.py (line appears 3 times in that last one), and changing the line

"model": self.pet.breed,

so that it reads

"model": "Dog",

in each file, then re-adding the integration, got all of my devices and entities to re-populate. All of them seem to be working fine again, and the workaround survived a hard reboot. I assume somewhere in the integration that would normally populate the dogs' breeds now simply shows "Dog" instead, but it's a small price to pay to get the integration up and running again, IMHO. Hope this helps a few people out of similar troubles.

**Comment by cladkins** [comment]
Just gave this a shot with Dog and Labradoodle. No joy.

**Comment by matthai5** [comment]
Same issue here, only base is working.

**Comment by mattfox27** [comment]
same issue

**Comment by eternistarr** [comment]
Same thing here. All my collars became unavailable. I cleared out the integration and readded it only base stations show up

**Comment by mattfox27** [comment]
> Found a workaround! Simply going into /config/custom_components/tryfi/ , editing binary_sensor.py, device_tracker.py, light.py, select.py, and sensor.py (line appears 3 times in that last one), and changing the line
> 
> "model": self.pet.breed,
> 
> so that it reads
> 
> "model": "Dog",
> 
> in each file, then re-adding the integration, got all of my devices and entities to re-populate. All of them seem to be working fine again, and the workaround survived a hard reboot. I assume somewhere in the integration that would normally populate the dogs' breeds now simply shows "Dog" instead, but it's a small price to pay to get the integration up and running again, IMHO. Hope this helps a few people out of similar troubles.

Is this fix still working?

**Comment by loafbutts** [comment]
The integration has remained functional for me since I made that post, but I'm still on the same install. No idea if it would still work if I tried to reinstall again. I'm not sure why it wouldn't work for cladkins back in July, unless a Fi update had already broken the workaround by then.

**Comment by mattfox27** [comment]
> The integration has remained functional for me since I made that post, but I'm still on the same install. No idea if it would still work if I tried to reinstall again. I'm not sure why it wouldn't work for cladkins back in July, unless a Fi update had already broken the workaround by then.

Ya I just wanted to check before trying your fix, ill give it a shot

Do you put your pets name in "model": "Dextrer"  or just like "model": "Dog",

**Comment by mattfox27** [comment]
> The integration has remained functional for me since I made that post, but I'm still on the same install. No idea if it would still work if I tried to reinstall again. I'm not sure why it wouldn't work for cladkins back in July, unless a Fi update had already broken the workaround by then.

So I made the changes and restarted HA and now it works awesome!!!!  Cool thanks for the help

**Comment by eternistarr** [comment]
> Found a workaround! Simply going into /config/custom_components/tryfi/ , editing binary_sensor.py, device_tracker.py, light.py, select.py, and sensor.py (line appears 3 times in that last one), and changing the line
> 
> "model": self.pet.breed,
> 
> so that it reads
> 
> "model": "Dog",
> 
> in each file, then re-adding the integration, got all of my devices and entities to re-populate. All of them seem to be working fine again, and the workaround survived a hard reboot. I assume somewhere in the integration that would normally populate the dogs' breeds now simply shows "Dog" instead, but it's a small price to pay to get the integration up and running again, IMHO. Hope this helps a few people out of similar troubles.

This didn't work for me :(

**Comment by mattfox27** [comment]
It worked for me...try restarting HA

**Comment by sbabcock23** [comment]
Released new version 0.0.21 with better error handling. Please @mattfox27 or @eternistarr if the latest version resolves the issue.

**Comment by mattfox27** [comment]
Awesome I'll check it out tonight

**Comment by eternistarr** [comment]
> Released new version 0.0.21 with better error handling. Please @mattfox27 or @eternistarr if the latest version resolves the issue.

No joy. I removed the integration completely and re added it. 
![Screenshot_20240102-153057](https://github.com/sbabcock23/hass-tryfi/assets/22775973/c6633d5c-025d-47ad-851b-72a2ccfc664b)

**Comment by mattfox27** [comment]
It's working for me

**Comment by eternistarr** [comment]
So I tried pairing the new update with that fix above changing 
"model": self.pet.breed,

so that it reads

"model": "Dog",

This also didn't work. The Integration stopped working soon as the cats nano chip was added to tryfi. I don't see any errors in logs or anything. Just the depreciation warnings.

**Comment by eternistarr** [comment]
Yup deleted the cats profile and my collars loaded up immediately

**Comment by pukiesa** [comment]
Having the same issue with only the base showing up after replacing a broken collar. Tried the "model dog" thing with no luck.

Has there been a fix for this?
