### ISSUE TITLE
Integration stopped working

### ISSUE THREAD

**Issue by smarthomeaf** [sbabcock23/hass-tryfi#84]
My Tryfi integration stopped working on both my production and test Home assistant.  Here are some of teh logs

`This error originated from a custom integration.

Logger: homeassistant
Source: custom_components/tryfi/device_tracker.py:84
integration: TryFi (documentation, issues)
First occurred: December 8, 2024 at 11:34:12 PM (5808 occurrences)
Last logged: 7:51:07 PM

Error doing job: Task exception was never retrieved (None)
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 267, in _handle_refresh_interval
    await self._async_refresh(log_failures=True, scheduled=True)
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 478, in _async_refresh
    self.async_update_listeners()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 177, in async_update_listeners
    update_callback()
    ~~~~~~~~~~~~~~~^^
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 558, in _handle_coordinator_update
    self.async_write_ha_state()
    ~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1023, in async_write_ha_state
    self._async_write_ha_state()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1148, in _async_write_ha_state
    self.__async_calculate_state()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1087, in __async_calculate_state
    if state_attributes := self.state_attributes:
                           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/device_tracker/config_entry.py", line 284, in state_attributes
    attr.update(super().state_attributes)
                ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/device_tracker/config_entry.py", line 196, in state_attributes
    if self.battery_level is not None:
       ^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/tryfi/device_tracker.py", line 84, in battery_level
    return self.pet.device.batteryPercent
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/pytryfi/fiDevice.py", line 58, in batteryPercent
    return self._batteryPercent
           ^^^^^^^^^^^^^^^^^^^^
AttributeError: 'FiDevice' object has no attribute '_batteryPercent'. Did you mean: 'batteryPercent'?`

**Comment by smarthomeaf** [comment]
After a week, it started working again today.
